### ISSUE TITLE
‘m’ is a rigid type variable bound: build failure with 8.0.1.20161022

### ISSUE THREAD

**Issue by ilovezfs** [kazu-yamamoto/logger#106]
Build log is here: https://gist.github.com/ilovezfs/c62fa40eb3f61569cb0e03f8cd3320a8

Several errors that look like

```
Control/Monad/Logger.hs:249:10: error:
    • Couldn't match type ‘m’ with ‘IdentityT m’
      ‘m’ is a rigid type variable bound by
        the instance declaration at Control/Monad/Logger.hs:249:10
      Expected type: IdentityT
                       m (Loc -> LogSource -> LogLevel -> LogStr -> IO ())
        Actual type: IdentityT
                       (IdentityT m) (Loc -> LogSource -> LogLevel -> LogStr -> IO ())
```

Commenting out https://github.com/kazu-yamamoto/logger/blob/master/monad-logger/Control/Monad/Logger.hs#L249-L264 seems to work around the problem.

**Comment by snoyberg** [comment]
Is there any reason to believe this is a bug in our package instead of in GHC itself? Have you reported this upstream?

**Comment by ilovezfs** [comment]
Nope, I've not reported it to GHC. The main reason to think it's the package is that of all of git-annex's many dependencies, this is the only one that failed to build out of the box.

**Comment by ilovezfs** [comment]
@snoyberg suggestion on IRC is

>I guess all the 'm's in the default declaration should be some new variable 'n's

**Comment by ilovezfs** [comment]
may be related to https://ghc.haskell.org/trac/ghc/ticket/12768 which so far seems to be "won't fix"

**Comment by ilovezfs** [comment]
RyanGlScott on IRC has traced this to http://git.haskell.org/ghc.git/commit/d2958bd08a049b61941f078e51809c7e63bc3354 but the current belief is that the breakage is intentional and the bug is in the package.

**Comment by RyanGlScott** [comment]
12768 is a different issue. (I'm currently investigating that separately. In any case, 12768 and this issue were not caused by the same GHC commit.)

I've opened [GHC Trac #12784](https://ghc.haskell.org/trac/ghc/ticket/12784) for this particular issue.

**Comment by snoyberg** [comment]
Thanks Ryan, I've subscribed to that Trac ticket.

**Comment by ilovezfs** [comment]
@snoyberg Thanks you for tagging a new release!
