### ISSUE TITLE
Fast-logger doesn't guarantee log entry order

### ISSUE THREAD

**Issue by qrilka** [kazu-yamamoto/logger#107]
In our app we use a thread pool created with `parallel-io` to execute some tasks. Also we use `fast-logger` to log their execution. And we were surprised seeing "job XYZ finished" appearing in log files before "job XYZ started". It appears `fast-logger` doesn't deal correctly with threads migrating between Haskell capabilities (`pustLogStr` uses `threadCapability` when choosing buffer).
As a workaround I've forked `parallel-io` to support pools with bound threads - https://github.com/qrilka/parallel-io/commit/19a9b18b3d7a3696b781b84339f27ab7326703bd
But probably that's some known issue with `fast-logger` and there is some better way around this?

**Comment by qrilka** [comment]
@kazu-yamamoto is this repository still maintained?

**Comment by kazu-yamamoto** [comment]
@qrilka Sorry for the delay. 31 Oct is a really bad day for Japanese...

As discussed in the comments in this article, the ordering of log messages over cores is not guaranteed in fast-logger: http://www.yesodweb.com/blog/2014/01/new-fast-logger

In other words, the log messages in fast-logger is partial ordering. If you have an idea to make it total ordering over cores, please let me know.

**Comment by qrilka** [comment]
Thanks for the response @kazu-yamamoto 
Regarding the ordering - at the moment I don't have concrete proposals but probably it's worth to have it mentioned in haddocks somewhere? Disqus comments in Yesod blog don't seem to be intuitive place to look into for such info in my opinion.

**Comment by kazu-yamamoto** [comment]
Documentation is a good thing. Would you send me a pull request?

**Comment by kazu-yamamoto** [comment]
Ping @qrilka.
I would like to release a new version after updating the doc.

**Comment by kazu-yamamoto** [comment]
Let's close.
