### ISSUE TITLE
How do I use a TimedFastLogger?

### ISSUE THREAD

**Issue by abailly** [kazu-yamamoto/logger#109]
I understand `FastLogger :: LogStr -> IO ()` but don't understand the type of `TimedFastLogger:: (FormattedTime -> LogStr) -> IO ()`. How do I pass the actual string to log to such a logger?

**Comment by alexbiehl** [comment]
`TimedFastLogger` is defined as higher-order function. You can write your log function like this:

```haskell
log :: TimedFastLogger -> LogStr -> IO ()
log l s = l (\time -> time <> " " <> s)
```

You close over your message `LogStr` and the `TimedFastLogger` executes it.
