### ISSUE TITLE
bytestring-builder is not necessary on newer ghc

### ISSUE THREAD

**Issue by QuLogic** [kazu-yamamoto/logger#112]
If I understand [the description](https://hackage.haskell.org/package/bytestring-builder) correctly, `bytestring-builder` should not be necessary on ghc 7.8. The package is supposed to be smart enough to be empty on those versions, but it would be nice if the packages here could be configured in such a way as to not require them it at all.

**Comment by kazu-yamamoto** [comment]
Feel free to add `if impl(ghc < VER)` to `fast-logger.cabal` and send me a PR.
