### ISSUE TITLE
Add Semigroup instance to LogStr

### ISSUE THREAD

**Issue by kseo** [kazu-yamamoto/logger#114]
`LogStr` does not have an instance of `Semigroup`. This does not interact well with classy-prelude which provides `(<>)` operator defined in `Semigroup`.

**Comment by kazu-yamamoto** [comment]
Ah. A pull request is welcome!

**Comment by kseo** [comment]
👌 I created a PR #115

**Comment by kazu-yamamoto** [comment]
Let's close.
