### ISSUE TITLE
installing fast-logger-2.4.8 using cabal install on Windows fails

### ISSUE THREAD

**Issue by Demki** [kazu-yamamoto/logger#118]
On a fresh minimal ghc build, fast-logger-2.4.7 installs fine.  
The error message:  
```
Building fast-logger-2.4.8...
Preprocessing library fast-logger-2.4.8...

System\Log\FastLogger\FileIO.hs:15:0: error:
     error: macro names must be identifiers
     #ifdef !MIN_VERSION_win32(2,3,1,0)
     ^
`gcc.exe' failed in phase `C pre-processor'. (Exit code: 1)
```

**Comment by kazu-yamamoto** [comment]
A new version has been released to fix this issue.

**Comment by Nezteb** [comment]
To anyone who stumbles on this issue:

I ran into this issue because `servant-server` and/or `warp` rely on the 2.4.8 version of this library. I fixed the build error by moving from Stackage LTS 7.18 to 7.20 and updating the cabal file `build-depends` versions.
