### ISSUE TITLE
log to multiple backends

### ISSUE THREAD

**Issue by epsilonhalbe** [kazu-yamamoto/logger#132]
Is it possible to log to say a file and stderr at the same time with monad-logger?

**Comment by snoyberg** [comment]
Yes, you'd have to write a custom function that sends the data to both locations and then use `runLoggingT` on that function. But there's nothing in the package that does such logging out-of-the-box.

**Comment by epsilonhalbe** [comment]
Thanks for the info - maybe I'll add that functionality, saw that in logging-effects - and used it to log all messages to stdout but only messages with loglevel above debug to a file.
