### ISSUE TITLE
Outdated reference to GHandler

### ISSUE THREAD

**Issue by MaxGabriel** [kazu-yamamoto/logger#149]
The [Control.Monad.Logger docs](https://www.stackage.org/haddock/lts-9.17/monad-logger-0.3.25.1/Control-Monad-Logger.html#v:runLoggingT) say:

> The MonadLogger class is implemented by monads that give access to a logging facility. If you're defining a custom monad, then you may define an instance of MonadLogger that routes the log messages to the appropriate place (e.g., that's what yesod-core's GHandler does). Otherwise, you may use the LoggingT monad included in this module (see runStderrLoggingT). To simply discard log message, use NoLoggingT.

IIRC, yesod hasn't had a `GHandler` type for awhile, so I think this reference is outdated

**Comment by snoyberg** [comment]
Good catch, thanks!
