### ISSUE TITLE
NoLoggingT does not implement generalBracket for exceptions >= 0.9

### ISSUE THREAD

**Issue by ajscholl** [kazu-yamamoto/logger#158]
It seems like exceptions 0.9 now requires the implementation of a third function, `generalBracket` [1], for the MonadMask typeclass. As there is no upper bound on exceptions, this currently causes a crash if the function is called.

[1] https://hackage.haskell.org/package/exceptions-0.9.0/docs/Control-Monad-Catch.html#v:generalBracket

**Comment by snoyberg** [comment]
I've added such support on master at c0707e7d511d490e78fd79118a1de3aa76690743. Can you test this out and, if it fixes the issue for you, I'll cut a release. Thanks for the report.

**Comment by snoyberg** [comment]
I've made a release, which includes 0.10.0 support as well.
