### ISSUE TITLE
Could we get a retrospective upper-bound on exceptions?

### ISSUE THREAD

**Issue by ocharles** [kazu-yamamoto/logger#163]
Just experienced a runtime crash at work because we're using https://hackage.haskell.org/package/monad-logger-0.3.28.1 with https://hackage.haskell.org/package/exceptions-0.10.0. These are not compatible, because that version of `monad-logger` doesn't define `generalMask` (or whatever it's called) in `MonadMask`. Could a revision be added that adds an upper-bound?

**Comment by snoyberg** [comment]
I don't typically do retroactive edits for these cases. If you'd like maintainer access on Hackage, happy to grant it, and you can knock yourself out with (sensible) retroactive upper bounds.

**Comment by kazu-yamamoto** [comment]
The new repo of `monad-logger` is https://github.com/snoyberg/monad-logger
I would like to close this.
