### ISSUE TITLE
Move monad-logger to separate repo?

### ISSUE THREAD

**Issue by snoyberg** [kazu-yamamoto/logger#164]
Pinging @kazu-yamamoto. What do you think about me moving `monad-logger` to a separate repo? I'm thinking it may simplify issue tracking and CI maintenance. Concretely, the recent changes to only test with `new-build` have me concerned that bugs with `cabal build` will no longer be detected.

**Comment by kazu-yamamoto** [comment]
No problem. You should do what you would like to do.
