### ISSUE TITLE
Suboptimal ToLogStr instance for Lazy ByteString

### ISSUE THREAD

**Issue by andrewthad** [kazu-yamamoto/logger#169]
The `ToLogStr` instance for lazy bytestring converts the lazy bytestring to a strict bytestring. This is unnecessary since `Data.ByteString.Builder.lazyByteString` pulls the chunks of a lazy bytestring straight into a builder.

**Comment by chessai** [comment]
I believe this is fixed in the most recent version

**Comment by andrewthad** [comment]
Nope, the instance still looks just like it does when I opened this issue:

```
instance ToLogStr BL.ByteString where
    toLogStr = toLogStr . S8.concat . BL.toChunks
```

Preferable would be:

```
instance ToLogStr BL.ByteString where
    toLogStr b = LogStr (fromIntegral (BL.length b)) (B.lazyByteString b)
```

**Comment by chessai** [comment]
@andrewthad i looked at the wrong instance. so nevermind then

**Comment by kazu-yamamoto** [comment]
@andrewthad Sorry, I didn't notice this. Could you send a PR?
