### ISSUE TITLE
ToLogStr instances for Int and Word

### ISSUE THREAD

**Issue by andrewthad** [kazu-yamamoto/logger#175]
I frequently work with `Int` and `Word` values that I need to include in log messages. In almost all cases, I want these to be represented in decimal (not hexadecimal or binary). I was wondering what the maintainers' thoughts were on adding `ToLogStr` instances for `Int` and `Word`. The argument against it is that there's more than one way to encode an int. However, this typeclass exists more for convenience than anything else, so maybe this is alright.

**Comment by chessai** [comment]
Seconded. Int{,8,16,32,64} and Word{,8,16,32,64} instances using ByteString Builder would be useful.

**Comment by kazu-yamamoto** [comment]
PR is highly welcome. :-)

**Comment by andrewthad** [comment]
Pull request at https://github.com/kazu-yamamoto/logger/pull/177
