### ISSUE TITLE
Consider exporting LogStr

### ISSUE THREAD

**Issue by MichaelXavier** [kazu-yamamoto/logger#184]
I frequently work with libraries that expose their logging API via `LogStr`, e.g. persistent. I would like to route these log messages to a different logging system but `LogStr` does not export sufficient constructors to do so. I was wondering if you'd be open to creating an `Internal` module tree and exporting basically what you've got in `System.Log.FastLogger.LogStr` right now. I'd even say you could just rename that module. This would of course carry the caveat that the API can break any time under the Internal module.

As it stands right now, for every log message I will have to `show` it to convert it from a builder to a string, then convert that back into the same exact `Builder` type for my log sink.

**Comment by kazu-yamamoto** [comment]
Yes. `Internal` makes sense to me. Would you send a PR?
