### ISSUE TITLE
SingleLogger misses and repeats log messages

### ISSUE THREAD

**Issue by vshabanov** [kazu-yamamoto/logger#210]
```haskell
import System.Log.FastLogger
import Control.Monad

main = do
    (put, close) <- newFastLogger1 $ LogStdout 2
    forM_ [1..10] $ \ i -> put $ toLogStr $ show i <> "\n"
    close
```
outputs
```
2
3
4
5
6
7
8
9
9
10
```

I suspect the issue is in 
https://github.com/kazu-yamamoto/logger/blob/61a78fc77a7343f15b764614e3cb4b9e1e7873bd/fast-logger/System/Log/FastLogger/SingleLogger.hs#L94
it drops `ologmsg` and repeats `nlogmsg`.

**Comment by kazu-yamamoto** [comment]
@vshabanov You are right. Would you send a PR?

**Comment by kazu-yamamoto** [comment]
I think `nlogmsg:q` should be `ologmsg:q`.
