### ISSUE TITLE
Test suite failure on Linux/x86_64

### ISSUE THREAD

**Issue by peti** [kazu-yamamoto/logger#42]
A complete build log is at <http://hydra.cryp.to/build/144214/nixlog/1/raw>.

**Comment by juhp** [comment]
I just hit this while building stackage nightly:

```
Test suite doctest: RUNNING...
### Failure in ./Network/Wai/Logger/Apache.hs:30: expression `import Network.Wai.Test'
expected: 
 but got: 
          <no location info>:
              Could not find module ‘Network.Wai.Test’
              It is not a module in the current program, or in any known package.
Examples: 15  Tried: 2  Errors: 0  Failures: 1
Test suite doctest: FAIL
```

**Comment by kazu-yamamoto** [comment]
You need to install `wai-extra` which cannot be added to dependencies due to cyclic dependencies.

**Comment by snoyberg** [comment]
Can't the dependency be added to just the test suite without causing cycle
issues?

**Comment by kazu-yamamoto** [comment]
No. `cabal install --only-dependencies --enable-tests` complains if `wai-extra` is added to the test suite.

**Comment by snoyberg** [comment]
That's unfortunate. Probably worth filing a bug with cabal. For the record, it works with stack, but I don't know if that will help out Nix at all.

**Comment by peti** [comment]
Well, it's possible to do some complicated bootstrapping in Nix to work around the problem, but I suppose it's simpler to just disable the test suite. :-(

**Comment by kazu-yamamoto** [comment]
I would close this issue. Please reopen if necessary.
