### ISSUE TITLE
pushLogStrLn

### ISSUE THREAD

**Issue by andrewthad** [kazu-yamamoto/logger#63]
I often find myself writing this function when I work with fast-logger:

    pushLogStrLn :: LoggerSet -> LogStr -> IO ()
    pushLogStrLn loggerSet logStr = pushLogStr loggerSet (logStr <> "\n")

Would this be a good addition to `fast-logger`?

**Comment by kazu-yamamoto** [comment]
Yes. Please give me a pull request.

**Comment by andrewthad** [comment]
Done.
