### ISSUE TITLE
Getting rid of defaultLoc showing in logs

### ISSUE THREAD

**Issue by greydot** [kazu-yamamoto/logger#69]
What would be the easiest way to achive that? Frankly, `@(<unknown>:<unknown> <unknown>:0:0)` in logs doesn't carry much information.

My first choice was deriving instance Eq Loc, and then comparing the loc argument in defaultLogStr with defaultLoc, but then it looks like a hack.

**Comment by greydot** [comment]
https://github.com/greydot/logger/commit/c684ada8b095e7ce2a0a4be8cf0459005b29f641

**Comment by snoyberg** [comment]
I've just pushed a commit that gets rid of the `defaultLoc` output, which I think is the right behavior for the library. Can you test it out before I release to Hackage?

**Comment by greydot** [comment]
Works for me. Thanks.

**Comment by snoyberg** [comment]
Cool, released to Hackage.
