### ISSUE TITLE
Question: How do I add MonadLogger to my Free monad?

### ISSUE THREAD

**Issue by joehillen** [kazu-yamamoto/logger#76]
How do I add `MonadLogger` to my transformer stack?

```haskell
data CraftDSL next
  = Exec  CraftEnv Command Args (Bool -> next)
  | FileRead CraftEnv FilePath (String -> next)
  | FileWrite CraftEnv FilePath String next
  deriving Functor


newtype Craft a = Craft { unCraft :: ReaderT CraftEnv (FreeT CraftDSL IO) a }
  deriving ( Functor, Monad, MonadIO, Applicative
           , MonadReader CraftEnv, MonadFree CraftDSL, MonadThrow)
```

I was able to add MonadThrow without issue; I was hoping adding MonadLogger would be just as easy.

I tried adding it and I get this error:

```
    No instance for (MonadLogger (FreeT CraftDSL IO))
      arising from the 'deriving' clause of a data type declaration
```

If I define an instance:

```haskell
instance MonadLogger (FreeT CraftDSL IO) where
  monadLoggerLog a b c d = Trans.lift $ monadLoggerLog a b c d
```

I get this error:

```
    Could not deduce (MonadLogger IO)
      arising from a use of ‘monadLoggerLog’
```

Any ideas? Sorry, if this is not an appropriate place to ask this.

**Comment by gregwebs** [comment]
Try just using `IO` for your example if you want to simplify things.

You need `LoggingT` or a `MonadLogger` constraint.

**Comment by joehillen** [comment]
> Try just using IO for your example if you want to simplify things.

I don't understand.

> You need LoggingT or a MonadLogger constraint.

Can you be more specific? Where exactly should I put `LoggingT` or `MonadLogger`?

**Comment by joehillen** [comment]
I push my code if that helps. https://github.com/joehillen/craft-monadfree/blob/master/app/Main.hs#L34

**Comment by joehillen** [comment]
Someone was able to help me with this on [StackOverflow](http://stackoverflow.com/a/35111764/334632).
