### ISSUE TITLE
runFileLoggingT or runHandleLoggingT

### ISSUE THREAD

**Issue by gbwey** [kazu-yamamoto/logger#82]
Hi,

Is there some way to use MonadLogger using a filename instead of stdout/stderr? 

Thanks

**Comment by snoyberg** [comment]
Yes: fast-logger has functions for creating a `LoggerSet` from a `FilePath` and to send `LogStr`s to a `LoggerSet`, and monad-logger has `defaultLogStr` and `runLoggingT`. Putting them together will allow logging to a file.

**Comment by gbwey** [comment]
Thanks, that helped. I have it setup now.
