### ISSUE TITLE
wai-logger broken due to new fast-logger

### ISSUE THREAD

**Issue by charleso** [kazu-yamamoto/logger#88]
`fast-logger` `2.4.4` has just been released to hackage, but it looks like the new version of `wai-logger` hasn't (yet), and the current version isn't source compatible.

```
Network/Wai/Logger.hs:230:11:
    Ambiguous occurrence ‘LogCallback’
    It could refer to either ‘Network.Wai.Logger.LogCallback’,
                             defined at Network/Wai/Logger.hs:108:16
                          or ‘System.Log.FastLogger.LogCallback’,
                             imported from ‘System.Log.FastLogger’ at Network/Wai/Logger.hs:60:1-28
```

**Comment by winterland1989** [comment]
It's because i move `LogType` to fast-logger in #85 , and it conflict with the old version of `LogType` defined in wai-logger, please wait @kazu-yamamoto judge on this.

**Comment by kazu-yamamoto** [comment]
@charleso fast-logger v2.4.4 was deprecated. I guess if you do "cabal update" again, v2.4.4 is never used.

**Comment by kazu-yamamoto** [comment]
Relating to #89.

**Comment by kazu-yamamoto** [comment]
This is fixed. Let's close.
