### ISSUE TITLE
No-TH logging with GHC8s CallStacks

### ISSUE THREAD

**Issue by alexbiehl** [kazu-yamamoto/logger#93]
Hello, 

I've been toying around with GHC 8s CallStack lately. Maybe this is something you are interested in as well! It eliminates the need for template haskell to have precise source location in your logs. 

Here, a little example: 

``` haskell
logWithCS :: (?callstack::CallStack, MonadLogger m, ToLogStr msg) => LogLevel -> msg -> m ()
logWithCS level msg =
  case getCallStack ?callstack of
    ((_, srcLoc):_)
      -> monadLoggerLog (Loc { loc_filename = srcLocFile srcLoc
                             , loc_package  = srcLocPackage srcLoc
                             , loc_module   = srcLocModule srcLoc
                             , loc_start    = (srcLocStartLine srcLoc, srcLocStartCol srcLoc)
                             , loc_end      = (srcLocEndLine srcLoc, srcLocEndCol srcLoc)
                             } ) "" level msg
```

Running 

``` haskell
import Control.Monad.Logger

main :: IO ()
main = do

  runStdoutLoggingT $ do
    logWithCS LevelInfo "hello callstack"
```

results in : `[Info] hello callstack @(main:Main main.hs:7:5)`

**Comment by snoyberg** [comment]
Yes, I'm definitely interested in this, I'd intended to look into this but didn't get around to it yet. I'd be happy to take a PR on this. It may be worth putting these functions in a separate module so that the convenient names `logDebug`, `logInfo`, etc, can be used.

One comment on your implementation: I'd prefer if the functions were total. Is there any way that the `getCallStack ?callstack` function can return an empty list? I'm simply not familiar with the API yet.

**Comment by alexbiehl** [comment]
I will prepare one tomorrow. What would you like the module be called? Control.Monad.Logger....? 

Of course, this was quickly hacked together in enthusiasm. There is still something fishy the [GHC docs](https://github.com/ghc/ghc/blob/master/libraries/base/GHC/Stack/Types.hs#L126) explicitly says to *not* rely on the implicit param name `callback` but using the constraint `HasCallBack` does indeed infer an empty stack in my little example; maybe a GHC bug? Need more experiments to confirm. 

Also: there is some function missing getCallStack :: HasCallStack => CallStack. As otherwise there is no way to get the current `CallStack` without poking the implementation detail.

**Comment by snoyberg** [comment]
No strong feelings on naming, perhaps `Control.Monad.Logger.CallStack`, and re-exporting most of the functionality from `Control.Monad.Logger`. It could even make sense to have the CallStack versions of the functions exposed from the main module as well under a different name like you've done here.

**Comment by gregwebs** [comment]
This should be closed now.

**Comment by snoyberg** [comment]
Good catch, thanks.
